version: '3.8'

services:
  fairshare-app:
    build: .
    image: fairshare-app:latest
    container_name: fairshare
    ports:
      - "3005:3000"
    environment:
      - DB_PATH=/app/data/fairshare.db
    volumes:
      - ./data:/app/data
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
